import {ReactNode} from "react";

import './globals.css'
import {Selector} from "@/app/components/selector";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
      <html lang="en" data-theme="synthwave">
      <body className="bg-neutral">
      <div className="flex flex-col items-center">
        <div className="max-w-screen-md min-h-[100vh] w-full flex flex-col">

            <Selector/>

          {children}
        </div>
      </div>
      </body>
      </html>
  )
}
